import { Dimensions } from 'react-native';

const { height, width } = Dimensions.get('window');

const HEADER = {
  WIDTH: width,
  HEIGHT: 56
};

const REQUEST_DASHBOARD = 'REQUEST_DASHBOARD';
const REQUEST_DASHBOARD_SUCCESS = 'REQUEST_DASHBOARD_SUCCESS';
const REQUEST_DASHBOARD_FAILED = 'REQUEST_DASHBOARD_FAILED';

const REQUEST_DEVOTIONAL_LIST = 'REQUEST_DEVOTIONAL_LIST';
const REQUEST_DEVOTIONAL_LIST_SUCCESS = 'REQUEST_DEVOTIONAL_LIST_SUCCESS';
const REQUEST_DEVOTIONAL_LIST_FAILED = 'REQUEST_DEVOTIONAL_LIST_FAILED';

const SET_FONT_SIZE = 'SET_FONT_SIZE';

const listMonth = () => ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

export {
  HEADER,
  listMonth,
  REQUEST_DASHBOARD,
  REQUEST_DASHBOARD_SUCCESS,
  REQUEST_DASHBOARD_FAILED,
  REQUEST_DEVOTIONAL_LIST,
  REQUEST_DEVOTIONAL_LIST_SUCCESS,
  REQUEST_DEVOTIONAL_LIST_FAILED,
  SET_FONT_SIZE
}